name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rossjrw/pr-preview-action@v1
        with:
          branch: main
          target-directory: pr-preview/${{ github.event.number }}
          source-dir: .
